org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.vfs.watch=true

minecraft_version=1.21.4
forge_version=54.1.18
loader_version_range=[54,)
forge_version_range=[54,)
forge_gradle_major=7
era=classic
java_version=21
mapping_version=1.21.4
# pack.mcmeta fields
pack_description="deathpenalty resources"
pack_format_field="pack_format": 42

mod_id=deathpenalty
mod_name=Death Reduces Life Mod
mod_version=1.2.0
mod_group_id=com.liuge.deathpenalty
mod_authors=liuge
minecraft.libraries.url=https://mirrors.hkmc.online/libraries
#?????????????????