org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.vfs.watch=true

minecraft_version=1.21.8
forge_version=58.1.21
loader_version_range=[58,)
forge_version_range=[58,)
forge_gradle_major=7
era=eventbus7
java_version=21
mapping_version=1.21.8
# pack.mcmeta fields
pack_description="deathpenalty resources"
pack_format_field="pack_format": 64

mod_id=deathpenalty
mod_name=Death Reduces Life Mod
mod_version=1.2.0
mod_group_id=com.liuge.deathpenalty
mod_authors=liuge