org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.vfs.watch=true

minecraft_version=1.20
forge_version=46.0.14
loader_version_range=[46,)
forge_version_range=[46,)
forge_gradle_major=6
era=classic
java_version=17
mapping_version=1.20
# pack.mcmeta fields
pack_description={"text": "deathpenalty resources"}
pack_format_field="pack_format": 15

mod_id=deathpenalty
mod_name=Death Reduces Life Mod
mod_version=1.2.0
mod_group_id=com.liuge.deathpenalty
mod_authors=liuge